server.port=8090
spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=distributor-commission-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://distributor-commission-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/distributors/**,/api/commissions/**

spring.cloud.gateway.server.webflux.routes[2].id=fund-catalog-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://fund-catalog-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/schemes/**,/api/reference/**

spring.cloud.gateway.server.webflux.routes[3].id=nav-accounting-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://nav-accounting-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/nav/**,/api/accruals/**,/api/dividends/**

spring.cloud.gateway.server.webflux.routes[4].id=folio-kyc-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://folio-kyc-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/folios/**,/api/holdings/**,/api/kyc/**

spring.cloud.gateway.server.webflux.routes[5].id=transaction-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://transaction-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/transactions/**,/api/sips/**,/api/swp-mandates/**

spring.cloud.gateway.server.webflux.routes[6].id=compliance-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://compliance-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/compliance/**

spring.cloud.gateway.server.webflux.routes[7].id=notification-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webflux.routes[8].id=audit-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://audit-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/audit/**

spring.cloud.gateway.server.webflux.routes[9].id=dashboard-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://dashboard-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/dashboard/**

fundmatrix.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5175

fundmatrix.jwt.secret=ZGZramh1cnluaXNkeWl1ZnllODc3OWplaHJ3ZmRncnRlcnRlZ2ZyZXI4NzRld3I4NzRqaDd1NDNoNTdlcjM0dXVpcmV5dGg0M2c1Z2hqcmV0cmVm

logging.level.com.fundmatrix=INFO
