server.port=8081
spring.application.name=auth-user-service
server.servlet.context-path=/api
fundmatrix.jwt.secret=ZGZramh1cnluaXNkeWl1ZnllODc3OWplaHJ3ZmRncnRlcnRlZ2ZyZXI4NzRld3I4NzRqaDd1NDNoNTdlcjM0dXVpcmV5dGg0M2c1Z2hqcmV0cmVm

DB_NAME=auth_user_db
spring.datasource.url=jdbc:mysql://localhost:3306/auth_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
