server.port=8086
spring.application.name=compliance-service
server.servlet.context-path=/api

DB_NAME=compliance_db
spring.datasource.url=jdbc:mysql://localhost:3306/compliance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
# File logging with rotation (per-service log file)
logging.file.name=log/compliance-service.log

logging.level.com.fundmatrix.compliance=INFO
transaction-service.name=transaction-service
folio-kyc-service.name=folio-kyc-service
