server.port=8085
spring.application.name=folio-kyc-service
server.servlet.context-path=/api
DB_NAME=folio_kyc_db
spring.datasource.url=jdbc:mysql://localhost:3306/folio_kyc_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8


fund-catalog-service.name=fund-catalog-service
auth-user-service.name=auth-user-service
